# Generated by Django 4.1.3 on 2022-12-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stay_status',
            field=models.CharField(choices=[('STAY', 'STAY'), ('EXTEN', 'EXTENSION'), ('SHORT', 'SHORTENING'), ('LEAVE', 'LEAVE')], default='STAY', max_length=5),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('DEL', 'DELUXE'), ('PRE', 'PREMIUM'), ('REG', 'REGULAR')], max_length=3),
        ),
    ]
