# Generated by Django 4.1.3 on 2022-12-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_booking_stay_status_alter_roomtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
