# Generated by Django 4.1.3 on 2022-12-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_roomtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('DEL', 'DELUXE'), ('PRE', 'PREMIUM'), ('REG', 'REGULAR')], max_length=3),
        ),
    ]
