# Generated by Django 4.1.3 on 2022-12-15 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('official_title', models.CharField(blank=True, max_length=100)),
                ('identification', models.CharField(choices=[('PASSPORT', 'PASSPORT'), ('IDCARD', 'ID CARD'), ('DRIVERLICENSE', "DRIVER'S LICENSE")], default='PASSPORT', max_length=50)),
                ('payment_type', models.CharField(choices=[('Creditcard', 'Creditcard'), ('Cheque', 'Cheque'), ('Cash', 'Cash')], default='Creditcard', max_length=50)),
                ('checked_in', models.BooleanField(default=True)),
                ('stay_adults_number', models.IntegerField(blank=True, null=True)),
                ('stay_kids_number', models.IntegerField(blank=True, null=True)),
                ('stay_elderlies_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
